[bot]
token = "TOKEN"
admin_ids = [ 123456789 ]
help_article = "https://teletype.in/@aerith_cbot/desc"

[db]
connection_string = "postgresql+asyncpg://root:root@db/aerith"

[openai]
token="TOKEN"
group_model = "gpt-5"
private_model = "gpt-5-mini"
private_support_model = "gpt-5"
summarizer_model = "gpt-5-nano"
memory_llm_model = "gpt-5-nano"
memory_embedder_model = "text-embedding-3-small"

[limits]
group_cooldown=14_400
group_generic_tokens_limit=100_000
group_per_user_tokens_limit=15_000
group_per_support_user_tokens_limit=30_000
group_per_user_max_other_usage_coeff=0.5
private_cooldown=14_400
private_tokens_limit=40_000
private_support_tokens_limit=70_000
group_max_context_tokens=50_000
private_max_context_tokens=30_000
private_support_max_context_tokens=70_000

[support]
price=299
price_for_telegram=29900
currency="RUB"
duration=2_678_400
nearest_buy_interval=172_800
provider_token="TOKEN"

[chroma]
host = "chroma"
port = 8000
