"""init

Revision ID: 11a41dd31016
Revises:
Create Date: 2025-02-25 16:10:38.557543

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11a41dd31016"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_states",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column("is_answering", sa.Boolean(), nullable=False),
        sa.Column("is_focused", sa.Boolean(), nullable=False),
        sa.Column("listening_streak", sa.Integer(), nullable=False),
        sa.Column("ignoring_streak", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
        sa.UniqueConstraint("thread_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_states")
    # ### end Alembic commands ###
