"""add is_notified field

Revision ID: 3c6ff7d8a5c4
Revises: 736df3ef8b57
Create Date: 2025-04-10 13:20:07.486091

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c6ff7d8a5c4"
down_revision: Union[str, None] = "736df3ef8b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_states",
        sa.Column("last_ignored_answer", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_states", "last_ignored_answer")
    # ### end Alembic commands ###
