"""remove unused fields

Revision ID: 4fde214637ab
Revises: 3c6ff7d8a5c4
Create Date: 2025-04-12 16:35:39.590645

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fde214637ab"
down_revision: Union[str, None] = "3c6ff7d8a5c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_states", "listening_streak")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_states",
        sa.Column("listening_streak", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
