"""add is_notified field

Revision ID: 736df3ef8b57
Revises: e20c03ca2deb
Create Date: 2025-04-09 12:51:57.442276

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "736df3ef8b57"
down_revision: Union[str, None] = "e20c03ca2deb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_supporters",
        sa.Column("is_notified", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_supporters", "is_notified")
    # ### end Alembic commands ###
