"""added stickers

Revision ID: 8f05e79659df
Revises: e15183bb6b0a
Create Date: 2025-02-27 13:14:46.898381

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f05e79659df"
down_revision: Union[str, None] = "e15183bb6b0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stickers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=False),
        sa.Column("set_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stickers_emoji"), "stickers", ["emoji"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stickers_emoji"), table_name="stickers")
    op.drop_table("stickers")
    # ### end Alembic commands ###
