"""create user_personal_context table

Revision ID: ccaaf76c889f
Revises: 3c6ff7d8a5c4
Create Date: 2025-04-13 17:27:18.169917

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccaaf76c889f"
down_revision: Union[str, None] = "3c6ff7d8a5c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_personal_context",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("context", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_personal_context")
    # ### end Alembic commands ###
