"""added message

Revision ID: e15183bb6b0a
Revises: 11a41dd31016
Create Date: 2025-02-26 00:22:30.008169

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e15183bb6b0a"
down_revision: Union[str, None] = "11a41dd31016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.drop_constraint("chat_states_thread_id_key", "chat_states", type_="unique")
    op.drop_column("chat_states", "thread_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_states", sa.Column("thread_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint("chat_states_thread_id_key", "chat_states", ["thread_id"])
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
