"""add limits

Revision ID: e20c03ca2deb
Revises: a3a725d794a7
Create Date: 2025-04-07 19:53:37.969536

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e20c03ca2deb"
down_revision: Union[str, None] = "a3a725d794a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_limit_entries",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("last_ref_time", sa.BigInteger(), nullable=False),
        sa.Column("remain_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "user_group_last_contacts",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("last_contacted_time", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "user_id"),
    )
    op.create_table(
        "user_supporters",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("end_timestamp", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users_group_limit_entries",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("last_ref_time", sa.BigInteger(), nullable=False),
        sa.Column("remain_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users_private_limit_entries",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("last_ref_time", sa.BigInteger(), nullable=False),
        sa.Column("remain_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.add_column(
        "chat_states",
        sa.Column("sleeping_till", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_states", "sleeping_till")
    op.drop_table("users_private_limit_entries")
    op.drop_table("users_group_limit_entries")
    op.drop_table("user_supporters")
    op.drop_table("user_group_last_contacts")
    op.drop_table("group_limit_entries")
    # ### end Alembic commands ###
